import type { LLCatalog, LLCatalogAttraction } from './types';

const mk: LLCatalogAttraction[] = [
  {
    id: 'mk-seven-dwarfs-mine-train',
    shortCode: 'sdmt',
    attractionLabel: 'Seven Dwarfs Mine Train',
    parkId: 'magic-kingdom',
    passType: 'individual',
    tier: null,
    heightRestriction: null,
  },
  {
    id: 'mk-tron-lightcycle-run',
    shortCode: 'tron',
    attractionLabel: 'TRON Lightcycle / Run',
    parkId: 'magic-kingdom',
    passType: 'individual',
    tier: null,
    heightRestriction: '48in+',
  },
  {
    id: 'mk-jungle-cruise',
    shortCode: 'jc',
    attractionLabel: 'Jungle Cruise',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'mk-peter-pans-flight',
    shortCode: 'ppf',
    attractionLabel: "Peter Pan's Flight",
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'mk-space-mountain',
    shortCode: 'sm',
    attractionLabel: 'Space Mountain',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'mk-tianas-bayou-adventure',
    shortCode: 'tba',
    attractionLabel: "Tiana's Bayou Adventure",
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'mk-big-thunder-mountain-railroad',
    shortCode: 'btmr',
    attractionLabel: 'Big Thunder Mountain Railroad',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: '40in+',
  },
  {
    id: 'mk-the-barnstormer',
    shortCode: 'barn',
    attractionLabel: 'The Barnstormer',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-buzz-lightyears-space-ranger-spin',
    shortCode: 'blsrs',
    attractionLabel: "Buzz Lightyear's Space Ranger Spin",
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-dumbo-the-flying-elephant',
    shortCode: 'dum',
    attractionLabel: 'Dumbo the Flying Elephant',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-haunted-mansion',
    shortCode: 'hm',
    attractionLabel: 'Haunted Mansion',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-its-a-small-world',
    shortCode: 'iasw',
    attractionLabel: '\u201cit\u2019s a small world\u201d',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-mad-tea-party',
    shortCode: 'mtp',
    attractionLabel: 'Mad Tea Party',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-the-magic-carpets-of-aladdin',
    shortCode: 'mca',
    attractionLabel: 'The Magic Carpets of Aladdin',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-the-many-adventures-of-winnie-the-pooh',
    shortCode: 'pooh',
    attractionLabel: 'The Many Adventures of Winnie the Pooh',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-mickeys-philharmagic',
    shortCode: 'phil',
    attractionLabel: "Mickey's PhilharMagic",
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-monsters-inc-laugh-floor',
    shortCode: 'milf',
    attractionLabel: 'Monsters Inc. Laugh Floor',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-pirates-of-the-caribbean',
    shortCode: 'poc',
    attractionLabel: 'Pirates of the Caribbean',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-tomorrowland-speedway',
    shortCode: 'ts',
    attractionLabel: 'Tomorrowland Speedway',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'mk-under-the-sea-journey-of-the-little-mermaid',
    shortCode: 'uts',
    attractionLabel: 'Under the Sea ~ Journey of The Little Mermaid',
    parkId: 'magic-kingdom',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
];

const epcot: LLCatalogAttraction[] = [
  {
    id: 'epcot-guardians-of-the-galaxy-cosmic-rewind',
    shortCode: 'gotr',
    attractionLabel: 'Guardians of the Galaxy: Cosmic Rewind',
    parkId: 'epcot',
    passType: 'individual',
    tier: null,
    heightRestriction: '42in+',
  },
  {
    id: 'epcot-frozen-ever-after',
    shortCode: 'fea',
    attractionLabel: 'Frozen Ever After',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'epcot-remys-ratatouille-adventure',
    shortCode: 'rra',
    attractionLabel: "Remy's Ratatouille Adventure",
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'epcot-test-track',
    shortCode: 'tt',
    attractionLabel: 'Test Track',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'epcot-disney-and-pixar-short-film-festival',
    shortCode: 'sff',
    attractionLabel: 'Disney and Pixar Short Film Festival',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-journey-into-imagination-with-figment',
    shortCode: 'fig',
    attractionLabel: 'Journey into Imagination with Figment',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-living-with-the-land',
    shortCode: 'lwl',
    attractionLabel: 'Living with the Land',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-mission-space',
    shortCode: 'ms',
    attractionLabel: 'Mission: SPACE',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-the-seas-with-nemo-and-friends',
    shortCode: 'snf',
    attractionLabel: 'The Seas with Nemo & Friends',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-soarin-around-the-world',
    shortCode: 'sal',
    attractionLabel: "Soarin' Around the World",
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-spaceship-earth',
    shortCode: 'se',
    attractionLabel: 'Spaceship Earth',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'epcot-turtle-talk-with-crush',
    shortCode: 'ttc',
    attractionLabel: 'Turtle Talk with Crush',
    parkId: 'epcot',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
];

const dhs: LLCatalogAttraction[] = [
  {
    id: 'dhs-star-wars-rise-of-the-resistance',
    shortCode: 'rotr',
    attractionLabel: 'Star Wars: Rise of the Resistance',
    parkId: 'hollywood-studios',
    passType: 'individual',
    tier: null,
    heightRestriction: '40in+',
  },
  {
    id: 'dhs-mickey-and-minnies-runaway-railway',
    shortCode: 'mmrr',
    attractionLabel: "Mickey & Minnie's Runaway Railway",
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'dhs-millennium-falcon-smugglers-run',
    shortCode: 'mfsm',
    attractionLabel: 'Millennium Falcon: Smugglers Run',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'dhs-rock-n-roller-coaster-starring-the-muppets',
    shortCode: 'rnrc',
    attractionLabel: "Rock 'n' Roller Coaster Starring The Muppets",
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'dhs-slinky-dog-dash',
    shortCode: 'sdd',
    attractionLabel: 'Slinky Dog Dash',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier1',
    heightRestriction: null,
  },
  {
    id: 'dhs-alien-swirling-saucers',
    shortCode: 'ass',
    attractionLabel: 'Alien Swirling Saucers',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-beauty-and-the-beast-live-on-stage',
    shortCode: 'batb',
    attractionLabel: 'Beauty and the Beast Live on Stage',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-for-the-first-time-in-forever-a-frozen-sing-along-celebration',
    shortCode: 'fsa',
    attractionLabel: 'For the First Time in Forever: A Frozen Sing-Along Celebration',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-indiana-jones-epic-stunt-spectacular',
    shortCode: 'ij',
    attractionLabel: 'Indiana Jones Epic Stunt Spectacular',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-star-tours-the-adventures-continue',
    shortCode: 'st',
    attractionLabel: 'Star Tours \u2013 The Adventures Continue',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-the-little-mermaid-a-musical-adventure',
    shortCode: 'tlm',
    attractionLabel: 'The Little Mermaid \u2013 A Musical Adventure',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-the-twilight-zone-tower-of-terror',
    shortCode: 'tzt',
    attractionLabel: 'The Twilight Zone Tower of Terror\u2122',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
  {
    id: 'dhs-toy-story-mania',
    shortCode: 'tsm',
    attractionLabel: 'Toy Story Mania!',
    parkId: 'hollywood-studios',
    passType: 'multipass',
    tier: 'tier2',
    heightRestriction: null,
  },
];

const dak: LLCatalogAttraction[] = [
  {
    id: 'dak-avatar-flight-of-passage',
    shortCode: 'afp',
    attractionLabel: 'Avatar Flight of Passage',
    parkId: 'animal-kingdom',
    passType: 'individual',
    tier: null,
    heightRestriction: '44in+',
  },
  {
    id: 'dak-expedition-everest-legend-of-the-forbidden-mountain',
    shortCode: 'ee',
    attractionLabel: 'Expedition Everest \u2013 Legend of the Forbidden Mountain',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-feathered-friends-in-flight',
    shortCode: 'fff',
    attractionLabel: 'Feathered Friends in Flight!',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-festival-of-the-lion-king',
    shortCode: 'flk',
    attractionLabel: 'Festival of the Lion King',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-finding-nemo-the-big-blue-and-beyond',
    shortCode: 'nemo',
    attractionLabel: 'Finding Nemo: The Big Blue... and Beyond!',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-kali-river-rapids',
    shortCode: 'krr',
    attractionLabel: 'Kali River Rapids',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-kilimanjaro-safaris',
    shortCode: 'ks',
    attractionLabel: 'Kilimanjaro Safaris',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-navi-river-journey',
    shortCode: 'nrj',
    attractionLabel: 'Na\u02BBvi River Journey',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
  {
    id: 'dak-zootopia-better-zoogether',
    shortCode: 'zoo',
    attractionLabel: 'Zootopia: Better Zoogether!',
    parkId: 'animal-kingdom',
    passType: 'multipass',
    tier: 'notier',
    heightRestriction: null,
  },
];

export const llCatalog: LLCatalog = {
  'magic-kingdom': {
    parkId: 'magic-kingdom',
    parkLabel: 'Magic Kingdom',
    hasTiers: true,
    maxTier1: 1,
    maxTier2: 2,
    maxMultiPass: 0,
    attractions: mk,
  },
  epcot: {
    parkId: 'epcot',
    parkLabel: 'EPCOT',
    hasTiers: true,
    maxTier1: 1,
    maxTier2: 2,
    maxMultiPass: 0,
    attractions: epcot,
  },
  'hollywood-studios': {
    parkId: 'hollywood-studios',
    parkLabel: "Disney's Hollywood Studios",
    hasTiers: true,
    maxTier1: 1,
    maxTier2: 2,
    maxMultiPass: 0,
    attractions: dhs,
  },
  'animal-kingdom': {
    parkId: 'animal-kingdom',
    parkLabel: "Disney's Animal Kingdom",
    hasTiers: false,
    maxTier1: 0,
    maxTier2: 0,
    maxMultiPass: 3,
    attractions: dak,
  },
};
